"""The dead, as the client will actually receive them.

Run:  python tests/test_creature_sheets.py   (from server/)

THREE CONTRACTS, AND NONE OF THEM HAS A RUNTIME SYMPTOM.

  1. **Every creature has a corpse, and every accessory has one too.** A
     missing `-death` folder is not an error in the client — `loadCharacterSheet`
     warns and returns null, the body simply stops being drawn on the frame it
     dies, and what the player sees is a zombie that vanishes. The same hole in
     a `zhat-*` is a cap that stays hanging in the air where the head used to
     be, which is the loudest possible bug in a corpse.
  2. **The sheets are the shape the renderer assumes.** Four rows (down, left,
     right, up) by three walk columns; a death sheet is a one-shot timeline of
     at least three. Nothing at runtime checks this: a sheet processed at the
     wrong grid draws a slice of the neighbouring frame and reads as glitch art.
  3. **THE VARIANTS ARE DIFFERENT SHAPES, not different palettes.** This is the
     one worth having. S15's test is to draw them in solid black and see if you
     can still tell them apart, and for a long time you could not: one head box,
     one body box, one stride, three colour schemes. That is invisible to every
     other check in this repository — the sheets load, the grids match, the game
     runs, and the forest is full of one creature wearing three coats. Here it
     is arithmetic: take each creature's alpha mask and count the pixels that
     differ. Recolour one of these creatures into another and this fails.
  4. **THE WOLVES HAVE THE RIGHT NUMBER OF HEADS.** Counting heads is not a
     thing a computer can do to a picture, but counting EYES is: every
     creature in this game carries one lit accent pixel per socket, and the
     wolf sheets are generated by fanning ONE head painter N times
     (`make_wolf.Build.heads`). So the face-on frame carries exactly two
     embers per head, and if a head stops being drawn -- an offset pushed off
     the frame, a fan that silently clipped -- the count drops and nothing
     else in this repository notices. The whole miniboss reads off "three
     lights moving together in the dark"; two is a different creature.
  5. **AND THE SLEEPING ONE CARRIES NONE.** A lit socket is this game's word
     for "it has noticed you". The alpha's telegraph is that the den is dark
     until it wakes, so one ember on the sleep sheet would be the art saying
     the opposite of what the simulation is doing, on the one frame the whole
     encounter is decided from.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

from PIL import Image  # noqa: E402

from make_zombie import EYE  # noqa: E402

PROCESSED = Path(__file__).resolve().parents[2] / "assets/processed"

#: THE one accent hue in the game (S12). Imported rather than typed, so a
#: retuned eye retunes the test instead of breaking it.
EMBER = EYE[4][:3]

#: Creatures that share a frame grid and must not share a shape. Compared
#: WITHIN a family, never across one: a wolf and a zombie are not the same
#: size, and the recolour failure this test exists to catch is a failure
#: between siblings on one sheet.
FAMILIES = (
    ("zombie", "zombie-husk", "zombie-brute", "zombie-bloater"),
    ("wolf", "wolf-twin", "wolf-alpha"),
)
CREATURES = tuple(name for family in FAMILIES for name in family)
#: Eyes per head, face-on. `make_wolf._eyes_front` lights both sockets on the
#: down facing -- head-on there is nothing turned away -- so the count is the
#: head count doubled.
EYES_PER_HEAD = 2
#: How many heads each wolf sheet is supposed to have. It is the whole point
#: of the creature and nothing at runtime can tell.
WOLF_HEADS = {"wolf": 1, "wolf-twin": 2, "wolf-alpha": 3}
#: The sleeping pose: a state rather than an event, so it loops and it has no
#: death timeline of its own.
SLEEP_SHEETS = ("wolf-alpha-sleep",)
ACCESSORIES = (
    "zhat-cap",
    "zhat-beanie",
    "zhat-hardhat",
    "zcloth-vest",
    "zcloth-jacket",
    "zcloth-tie",
)
#: Only the ACCESSORIES are locked to this: they are drawn on a 16x16 body.
#: A creature carries its own frame size in its manifest -- a quadruped is
#: wider than it is tall -- so everything below measures rather than assumes.
#: The old blanket constant WAS the assumption, and it is what would have
#: silently cropped the first wolf into a zombie-shaped box.
TILE = 16
ROWS = 4
WALK_COLUMNS = 3
#: How many pixels of one frame's mask two creatures must disagree about
#: before they count as two creatures. The three that pass today are 34, 35
#: and 59 apart out of roughly a hundred lit pixels each, so this floor leaves
#: about a quarter of the smallest margin — enough that a legitimate tweak to
#: a stride or an arm does not trip it, and nowhere near enough for a recolour.
SILHOUETTE_MIN = 26
#: Columns of the UPPER PROFILE that have to differ, and this is the sharper
#: half of the test: S15 says the top contour is what carries an asset's
#: identity, so two creatures telling the same story about where their head
#: and shoulders are is the failure even if the rest of the mask disagrees.
#: Today's three differ over 10, 12 and 12 columns of sixteen.
CONTOUR_MIN = 7


def sheet(name: str) -> Image.Image:
    path = PROCESSED / name / "sheet.png"
    assert path.exists(), f"{name}: no processed sheet — run process_sprites.py"
    return Image.open(path).convert("RGBA")


def grid(name: str) -> tuple[int, int]:
    """(frame width, frame height) as the manifest declares them.

    READ, NOT ASSUMED. The renderer takes the frame size off this same file
    (`SpriteSheet.frameWidth`), so a test that hardcoded sixteen would be
    checking a different sheet than the game draws the moment a creature
    stops being a person.
    """
    manifest = json.loads((PROCESSED / name / "manifest.json").read_text())
    return manifest["frameWidth"], manifest["frameHeight"]


def frame(name: str, column: int = 1, row: int = 0) -> Image.Image:
    width, height = grid(name)
    return sheet(name).crop(
        (column * width, row * height, (column + 1) * width, (row + 1) * height)
    )


def mask(name: str, column: int = 1) -> set[tuple[int, int]]:
    """The silhouette of one frame: every pixel that is not transparent."""
    width, height = grid(name)
    pixels = frame(name, column).load()
    return {
        (x, y)
        for y in range(height)
        for x in range(width)
        if pixels[x, y][3] > 0
    }


def contour(name: str) -> dict[int, int | None]:
    """The upper profile: the first lit row in each column, or None."""
    silhouette = mask(name)
    width, _ = grid(name)
    profile: dict[int, int | None] = {}
    for x in range(width):
        column = [y for (px, y) in silhouette if px == x]
        profile[x] = min(column) if column else None
    return profile


def embers(name: str, column: int = 1) -> int:
    """Lit accent pixels on one face-on frame.

    The accent is ONE colour for every creature in the game (S12 allows
    exactly one), so this counts sockets with something still burning in them
    rather than guessing at a colour range that would drift the first time
    somebody warmed the pelt up.
    """
    pixels = frame(name, column).load()
    width, height = grid(name)
    return sum(
        1
        for y in range(height)
        for x in range(width)
        if pixels[x, y][:3] == EMBER
    )


def check_grids(names, dies: bool = True) -> None:
    for name in names:
        width, height = grid(name)
        walk = sheet(name)
        assert walk.height == height * ROWS, (
            f"{name}: {walk.height}px tall, expected {height * ROWS} "
            f"(down / left / right / up)"
        )
        assert walk.width == width * WALK_COLUMNS, (
            f"{name}: {walk.width}px wide, expected {width * WALK_COLUMNS} walk frames"
        )
        if not dies:
            continue
        dead = sheet(f"{name}-death")
        dead_w, dead_h = grid(f"{name}-death")
        assert (dead_w, dead_h) == (width, height), (
            f"{name}-death: {dead_w}x{dead_h} frames against the body's "
            f"{width}x{height}. A corpse drawn on another grid jumps on the "
            f"frame it dies"
        )
        assert dead.height == dead_h * ROWS, f"{name}-death: wrong row count"
        columns = dead.width // dead_w
        assert columns >= 3, (
            f"{name}-death: {columns} frames — a collapse is a timeline, not a swap"
        )


def main() -> None:
    check_grids(CREATURES + ACCESSORIES)
    # The sleep pose is a STATE, not an event: it loops, and it never dies.
    check_grids(SLEEP_SHEETS, dies=False)

    # S15, as arithmetic. Down-facing idle, which is the pose a player meets.
    masks = {name: mask(name) for name in CREATURES}
    for family in FAMILIES:
        for first in range(len(family)):
            for second in range(first + 1, len(family)):
                one, other = family[first], family[second]
                if grid(one) != grid(other):
                    # Two different frame sizes are two different shapes by
                    # construction, and comparing masks across two grids
                    # measures the size difference and nothing else.
                    continue
                apart = len(masks[one] ^ masks[other])
                assert apart >= SILHOUETTE_MIN, (
                    f"{one} and {other} are the same shape ({apart} pixels apart). "
                    f"A variant is an anatomy, not a palette — see make_zombie.py"
                )
                profiles = contour(one), contour(other)
                width = grid(one)[0]
                columns = sum(
                    1 for x in range(width) if profiles[0][x] != profiles[1][x]
                )
                assert columns >= CONTOUR_MIN, (
                    f"{one} and {other} have the same top contour ({columns} columns "
                    f"differ). S15: the upper profile is the identity — distinguish "
                    f"them by head and shoulder, not by colour"
                )

    # And each of them has to BE a creature: something in the top half (a head)
    # and something in the bottom (legs it stands on). A sheet that processed
    # to an empty or clipped frame passes every check above.
    for name, silhouette in masks.items():
        height = grid(name)[1]
        assert any(y < height // 2 for _, y in silhouette), f"{name}: no head"
        assert any(y >= height - 3 for _, y in silhouette), f"{name}: nothing to stand on"

    # COUNT THE LIGHTS. See the header: one lit socket per eye, two eyes per
    # head face-on, and the head count IS the creature.
    for name, heads in WOLF_HEADS.items():
        lit = embers(name)
        assert lit == heads * EYES_PER_HEAD, (
            f"{name}: {lit} lit sockets face-on, expected "
            f"{heads * EYES_PER_HEAD} ({heads} heads x {EYES_PER_HEAD}). "
            f"A head that stopped being drawn is invisible to every other "
            f"check here — see make_wolf.Build.heads"
        )
    for name in SLEEP_SHEETS:
        for column in range(sheet(name).width // grid(name)[0]):
            assert embers(name, column) == 0, (
                f"{name} frame {column} carries a lit socket. A sleeping "
                f"creature wearing the accent is the art saying it has noticed "
                f"you, on the one frame the whole encounter is decided from"
            )

    print(
        f"ok ({len(CREATURES)} creatures, {len(ACCESSORIES)} accessories, "
        f"{sum(WOLF_HEADS.values())} heads)"
    )


if __name__ == "__main__":
    main()
